defineModule(sim, list(name = "LandR_MPB_studyArea", description = paste("Prepares 2 sets of objects needed for MPB + LandR-fireSense simulations in western Canada:", 
    "1. study areas and corresponding rasterToMatch (as well as large versions);", 
    "2. species equivalencies tables and the sppEquiv column;", 
    "Each is customized to the study area parameter passed as studyAreaName."), 
    keywords = "", authors = c(person(c("Alex", "M"), "Chubaty", 
        email = "achubaty@for-cast.ca", role = c("aut", "cre")), 
        person("Ian", "Eddy", email = "ian.eddy@nrcan-rncan.gc.ca", 
            role = "ctb")), childModules = character(0), version = list(LandR_MPB_studyArea = "0.0.2"), 
    timeframe = as.POSIXlt(c(NA, NA)), timeunit = "year", citation = list("citation.bib"), 
    documentation = deparse(list("README.md", "LandR_MPB_studyArea.Rmd")), 
    reqdPkgs = list("archive", "geodata", "ggplot2", "ggspatial", 
        "httr", "raster", "rgeos", "sf", "sp", "PredictiveEcology/mpbutils (>= 0.1.2)", 
        "PredictiveEcology/reproducible@modsForLargeArchives (>= 1.2.8.9033)", 
        "PredictiveEcology/LandR@development (>= 1.1.0.9020)"), 
    parameters = rbind(defineParameter("bufferDist", "numeric", 
        20000, NA, NA, "Distance (m) to buffer studyArea and rasterToMatch when creating 'Large' versions."), 
        defineParameter("ecoregions4studyArea", "integer", c(112, 
            120, 122, 124, 126), NA, NA, "National ecoregion ids to include in `studyArea`; should align with ecoprovinces used in `studyAreaName`."), 
        defineParameter("studyAreaName", "character", "ABSK_9.2", 
            NA, NA, paste("Should include 'ABSK' to identify the provinces in the study area.", 
                "May also include the ecoprovince ID in which to run the model.")), 
        defineParameter(".plotInitialTime", "numeric", NA, NA, 
            NA, "Describes the simulation time at which the first plot event should occur."), 
        defineParameter(".plotInterval", "numeric", NA, NA, NA, 
            "Describes the simulation time interval between plot events."), 
        defineParameter(".plots", "character", c("screen", "png"), 
            NA, NA, "Describes the simulation time interval between plot events."), 
        defineParameter(".saveInitialTime", "numeric", NA, NA, 
            NA, "Describes the simulation time at which the first save event should occur."), 
        defineParameter(".saveInterval", "numeric", NA, NA, NA, 
            "This describes the simulation time interval between save events."), 
        defineParameter(".useCache", "logical", FALSE, NA, NA, 
            paste("Should this entire module be run with caching activated?", 
                "This is generally intended for data-type modules, where stochasticity", 
                "and time are not relevant"))), inputObjects = bindrows(expectsInput("targetCRS", 
        "character", desc = "Geospatial projection to use.", 
        sourceURL = NA)), outputObjects = bindrows(createsOutput("absk", 
        "sf", "Alberta and Saskatchewan provincial boundaries"), 
        createsOutput("fireSenseForestedLCC", "integer", desc = "vector of LCC classes considered to be forested by fireSense."), 
        createsOutput("flammableRTM", "RasterLayer", desc = "RTM without ice/rocks/urban/water. Flammable map with 0 and 1."), 
        createsOutput("LCC", "RasterLayer", desc = "Land cover classification map, derived from national LCC 2005 product."), 
        createsOutput("missingLCCgroup", "character", "the group in `nonForestLCCGroups` that describes forested pixels omitted by LandR"), 
        createsOutput("nonflammableLCC", "integer", desc = "vector of LCC classes considered to be non-flammable"), 
        createsOutput("nonForestLCCGroups", "list", desc = "named list of non-forested landcover groups for fireSense"), 
        createsOutput("nontreeClasses", "integer", desc = "vector of LCC classes considered to be non-forested/treed."), 
        createsOutput("nonTreePixels", "integer", desc = "pixel indices indicating non-treed pixels"), 
        createsOutput("rasterToMatch", "RasterLayer", desc = "Raster to match, based on study area."), 
        createsOutput("rasterToMatchLarge", "RasterLayer", desc = "Raster to match (large) based on `studyAreaLarge.`"), 
        createsOutput("rasterToMatchReporting", "RasterLayer", 
            desc = "Raster to match based on `studyAreaReporting.`"), 
        createsOutput("speciesTable", "data.table", desc = "Species parameter table."), 
        createsOutput("sppColorVect", "character", desc = "Species colour vector."), 
        createsOutput("sppEquiv", "data.table", desc = "Species equivalency table."), 
        createsOutput("sppEquivCol", "character", desc = "name of column to use in `sppEquiv`."), 
        createsOutput("standAgeMap", "RasterLayer", desc = "Age (time since disturbance) map, derived from national kNN product."), 
        createsOutput("standAgeMap2001", "RasterLayer", desc = "raster of time since disurbance for year 2001."), 
        createsOutput("standAgeMap2011", "RasterLayer", desc = "raster of time since disurbance for year 2011."), 
        createsOutput("studyArea", "SpatialPolygons", desc = "Buffered study area in which to run simulations."), 
        createsOutput("studyAreaLarge", "SpatialPolygons", desc = "Buffered study area used for parameterization/calibration."), 
        createsOutput("studyAreaPSP", "SpatialPolygonsDataFrame", 
            paste("this area will be used to subset PSP plots before building the statistical model.", 
                "Currently PSP datasets with repeat measures exist only for Saskatchewan,", 
                "Alberta, Boreal British Columbia, and Ontario.")), 
        createsOutput("studyAreaReporting", "SpatialPolygons", 
            desc = "Unbuffered study area used for reporting/post-processing."))))
